server:
  port: 8080

spring:
  h2:
    console:
      enabled: true #h2 console enabled flag
      path: /h2-console  # console-path (localhost:8080/h2-console)
  # database information
  datasource:
    driver-class-name: org.h2.Driver  #h2 driver
    url: jdbc:h2:~/contents  # h2 connect path
    username: test  # username
    password: test1234 # user password
  # jpa setting
  jpa:
    hibernate:
      # create, create-drop, update, validate, none
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#feign client using api info
feign:
  target-api:
    kakao-blog-search:
      base-url: https://dapi.kakao.com/v2/search/blog
      rest-api-key: KakaoAK 669852b6abf4c397e36acc9c599c3e4b
    naver-blog-search:
      base-url: https://openapi.naver.com/v1/search/blog.json
      client-id: 4FQqUIIcfwqsa_tk_K7i
      client-secret: ksUWRhbc7D